### ISSUE TITLE
Curses!

### ISSUE THREAD

**Issue by hurrycaine** [ManageIQ/trollop#29]
The new runtime dependency, "curses" (aptly named) :O) , is causing me all kinds of havoc. I have not figured out the fix yet. I have tried installing dev Ruby packages. 
This is running on RHEL6 default system ruby 1.8.7

-bash-4.1# /usr/bin/gem install -v 2.0.6 --source http://blahblah/rubygems hiera-eyaml
Building native extensions.  This could take a while...
ERROR:  Error installing hiera-eyaml:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
    mkmf.rb can't find header files for ruby at /usr/lib/ruby/ruby.h

Gem files will remain installed in /usr/lib/ruby/gems/1.8/gems/curses-1.0.1 for inspection.
Results logged to /usr/lib/ruby/gems/1.8/gems/curses-1.0.1/ext/curses/gem_make.out

After installing a dev ruby the error changes to

Error: Could not update: Execution of '/usr/bin/gem install -v 2.0.1 --source http://blahblah.com/rubygems hiera-eyaml' returned 1: ERROR:  Error installing hiera-eyaml:
	ERROR: Failed to build gem native extension.

/usr/bin/ruby extconf.rb
checking for tgetent() in -ltinfo... no
checking for tgetent() in -ltermcap... no
checking for ncurses.h... no
checking for ncurses/curses.h... no
checking for curses_colr/curses.h... no
checking for curses.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

**Comment by Fryguy** [comment]
I was just talking to @kbrock today about this dependency and technically
it's an optional dependency, so we were considering removing it as a hard
dependency in the gemspec.

I'm sorry I don't see the solution in your particular issue.   Note that
Ruby 1.8 is completely unsupported by the Ruby core team and soon 1.9 will
be unsupported as well.  It's possible that the version of curses or its
dependencies do not support 1.8.6 either.

**Comment by jrafanie** [comment]
Curses.h is probably provided by libcurses or curses-devel. Try searching for that in yum. I'm not sure it will work even after that since those versions of ruby are not supported but the error you are seeing is the missing curses.h.

**Comment by Fryguy** [comment]
Thanks @jrafanie!  I completely missed that.

**Comment by kbrock** [comment]
I'll get rid of it.

Aside: I tried to start a conversation on rubygems to see if it makes sense to introduce an optional gem dependency much like gemspec has a development and runtime dependency.

**Comment by hurrycaine** [comment]
Thanks for the quick turnaround!

**Comment by kbrock** [comment]
@hurrycaine sure thing. Let us know if you run into any other problems.

I pushed 2.1.1
