### ISSUE TITLE
curses dependency breaks JRuby compatibility

### ISSUE THREAD

**Issue by tarcieri** [ManageIQ/trollop#33]
This gem no longer works on JRuby because it relies on the curses library, which uses an MRI C extension.

Perhaps you could use io/console instead?

**Comment by headius** [comment]
Specifically, this commit added a hard dependency on curses: 42bab27b13b7c8fd9e209027da5bbfb89bfa319c

Given that curses is a C ext that does not work on all impls, and there's [fallback logic](https://github.com/ManageIQ/trollop/blob/master/lib/trollop.rb#L523-L531) to use terminal width 80, it seems like curses should just be removed. If it is desired, you can still get terminal width on MRI and JRuby using the io/console library.

**Comment by Fryguy** [comment]
Fixed by #31

**Comment by Fryguy** [comment]
Thanks guys.   As mentioned in my comment in #31,  I think adding Jruby to the automated testing will prevent this in the future, so we'll do that too.

**Comment by kbrock** [comment]
thanks @headius and @Fryguy adding #34
