### ISSUE TITLE
Must have a short option?

### ISSUE THREAD

**Issue by rlpowell** [ManageIQ/trollop#52]
For rarely-used options I'd just as soon *not* have a short version, partly because short space is getting cluttered and partly so that for certain dangerous options the user has to actually type the whole thing out.

As far as I can tell there is no way to not have a short option for something.  Am I missing something?

**Comment by kbrock** [comment]
@rlpowell Hi. You can try `:short => :none` and that will allow you to forgo a short option.

If this does not work for you, please re-open this and I'll try and help more.

**Comment by rlpowell** [comment]
You are totally correct.  Sorry.

**Comment by kbrock** [comment]
@rlpowell thanks for mentioning this. I'll fix the docs.
