### ISSUE TITLE
Exit code from educate

### ISSUE THREAD

**Issue by jaredbeck** [ManageIQ/trollop#57]
`Trollop.educate` exits with code `0`.  I would like to use Trollop in an existing script, but usage errors must exit with a code N != `0`.  As a workaround, I can reopen Trollop:

```ruby
module Trollop
  def self.educate_without_exiting
    @last_parser.educate
  end
end

# somewhere in my code
Trollop.educate_without_exiting
exit(N)
```

Is there a better way for me to exit with a code N of my choosing?

PS: I'm using Trollop for the first time and I really like it so far.  Thanks for the lib!

**Comment by kbrock** [comment]
I'm mixed on this one.

If you specify `--help` on the command line, are you expecting a non 0 return status?

In your example, is help coming from a misuse, or an error?

**Comment by jaredbeck** [comment]
> If you specify --help on the command line, are you expecting a non 0 return status?

Good point.  If I'm requesting `--help`, I'd expect `0`.

> In your example, is help coming from a misuse, or an error?

Misuse, i.e. any time the usage is printed except for when `--help` is requested.

**Comment by kbrock** [comment]
@jaredbeck do you have a test case (not formally)

4 liner parse and opt blurb with a description of what you pass in on the command line and when you expect to get errors?

I can convert into an official test, just want to make sure I am coding up your case.

--Keenan

**Comment by jaredbeck** [comment]
Sure, let me see what I can come up with.  What if we consider `cp`?  It takes a variety of options and (usually) two arguments, a source path and a target path.  When only one argument is given, it prints usage and exits with a specific non-zero code.

It's my understanding that trollop is responsible only for options.  After parsing options, only the arguments are left in `ARGV`, right?  So, if we were implementing `cp`, we'd check the length of the remaining arguments.  If there were only one argument, we'd print usage and exit with that specific code.

Is that a good example?  Do you want me to take the next step and write an opt blurb for it?

**Comment by kbrock** [comment]
@jaredbeck No code. I had misunderstood you. pr 58 helped a lot.
I have what I consider a good fix, but am in the middle of a refactor in the test area.

If I don't merge in a fix for your issue by next friday, please ping me to keep me honest.

**Comment by kbrock** [comment]
After I get #61 in, I'll tack this on
