### ISSUE TITLE
how to add list of subcommands to help message

### ISSUE THREAD

**Issue by logicminds** [ManageIQ/trollop#70]
I want to add a list of subcommands to my help message so when I call Trollop.educate it allows the user to see a list of subcommands.  However, I am not sure how to customize the help message easily.

**Comment by jhaynes** [comment]
The help message is defined in `banner`. So you can do something like:
```ruby
subcommands = ['bar', 'baz']

Trollop::options do
  banner <<-EOS
Available subcommands are:
#{subcommands.join("\n")}
EOS
end

Trollop::educate
```
