### ISSUE TITLE
Documentation is somewhat lacking for examples

### ISSUE THREAD

**Issue by nanobowers** [ManageIQ/trollop#82]
I almost bailed on trollop due to perceived lack of features I needed, but eventually dug through the code comments to figure out what i wanted.  Much of this was b/c i found very few examples or how-to guides, other than the original documented example.

I'm willing to add _accessible_ examples, and was thinking of putting together a wiki on the github, as opposed to the currently visibile documentation that lives here: http://manageiq.github.io/trollop

OTOH, there is some documentation in the code that is accessible through ri/Rdoc, and duplication via wiki may violate DRY or otherwise get stale.  Thoughts?

**Comment by mckern** [comment]
More **accurate** and **accessible** is better/cheaper than worrying about DRY. I say write it out!

**Comment by nanobowers** [comment]
thanks for the encouragement!

**Comment by nanobowers** [comment]
@mckern @kbrock @Fryguy first cut of a github documentation via examples wiki at: https://github.com/nanobowers/trollop/wiki

**Comment by ddarbyson** [comment]
@nanobowers hey, thanks for writing this out... it helps do a quick catchup before getting into Trollop for the first time... much better than Thor so far... simple.

More examples for https://github.com/ManageIQ/trollop/blob/master/lib/trollop.rb#L179-L204 would be useful.

**Comment by nanobowers** [comment]
@ddarbyson Added two additional examples to cover your request.  
+ https://github.com/nanobowers/trollop/wiki/When-options-are-not-found
+ https://github.com/nanobowers/trollop/wiki/Git-style-optioning
If you notice other missing pieces, etc. please let me know.

**Comment by Fryguy** [comment]
@nanobowers Are you able to create this in the trollop wiki directly?

**Comment by Fryguy** [comment]
@nanobowers I love this documentation, and am going to put this directly into this repo's wiki  (with proper attribution of course)

**Comment by Fryguy** [comment]
...and done: https://github.com/ManageIQ/trollop/wiki created with all of the history from @nanobowers' repo

@nanobowers Thank you so much for documenting this!!

**Comment by nanobowers** [comment]
@Fryguy no problem, thanks for the inclusion.  It would be nice to have a link from the trollop README.md, as I don't think most people realize the wiki feature exists. 
feel free to close this issue.

**Comment by ddarbyson** [comment]
@nanobowers thanks for the contribution

**Comment by Fryguy** [comment]
> @Fryguy no problem, thanks for the inclusion. It would be nice to have a link from the trollop README.md, as I don't think most people realize the wiki feature exists.
feel free to close this issue.

@nanobowers That's a great idea...can you make a PR?

**Comment by Fryguy** [comment]
Closed in #90
