### ISSUE TITLE
Useful gem, but the name is offensive

### ISSUE THREAD

**Issue by macosgrove** [ManageIQ/trollop#92]
I love your work, but would you please consider renaming it.
The word 'trollop' is highly judgemental. It makes me shudder to see it.

Definition of trollop
: a vulgar or disreputable woman; especially : one who engages in sex promiscuously or for money
https://www.merriam-webster.com/dictionary/trollop

This is a word invented purely for putting down women who are either hard-up for money or who want to engage in physical pleasures that we wouldn't think twice about men engaging in.

I note that the makers of Factory Girl renamed their gem. https://github.com/thoughtbot/factory_bot/blob/master/NAME.md

**Comment by kbrock** [comment]
Hello @macosgrove 
Thank you for pushing this issue forward. #75 has stalled and there really is no reason for that.
I'll see what we can do to get this done

I'm closing in favor of #75 which I believe follows your same sentiment.
In that thread, we also referenced `FactoryBot`.

--Keenan

**Comment by macosgrove** [comment]
@kbrock Thanks very much!

**Comment by macosgrove** [comment]
@kbrock I see the gem has been renamed. Thanks so much for getting this done, I really appreciate it.
