### ISSUE TITLE
How to build sub-command switches

### ISSUE THREAD

**Issue by KINGSABRI** [ManageIQ/trollop#94]
Hello there, 
I've requirements here that I hope I explain it well. 

here is the case I'm trying to do
```
ruby cooltool.rb -m COMMAND --cmd-sw
# eg
ruby cooltool.rb -m module1 --list user.txt
```
since the `--list` switch belongs to `module1` not to `cooltool`

here's my initial dirty implementation 

**cooltool.rb**
```ruby

require 'trollop'
require 'pp'

module CoolTool
  class OptionParser
    attr_reader :main_opts

    def initialize
      @main_opts = Trollop::options do
        banner "Cool tool."
        banner "Options:"
        opt :parse, "Parse a string", :short => :p, :type => :string
        opt :module, "Use module", :short => :m, :default => ''
      end
    end

    def modules_list
      @modules_list = %w(module1 module2 module3)
    end
  end
end

opts = CoolTool::OptionParser.new
case
  when opts.main_opts[:parse]
    puts "Parsing!!"
  when opts.main_opts[:module]
    mod = opts.main_opts[:module]
    require "./#{mod}.rb"
    pp CoolTool::CoolToolModule.const_get(mod.capitalize).new
  else
    puts opts.main_opts
end
```

**module1.rb**
```ruby
module CoolTool
  module CoolToolModule
    class Module1
      attr_accessor :opts
      def initialize
        @opts = Trollop::Parser.new do
          banner "Module1."
          banner "Options:"
          opt :list, "The user list.", :short => :l, :type => :string
        end
        @opts.parse ARGV
      end

      # make module read the file if -l user.txt
      def run
        if @opts[:list]
          File.readlines(@opts[:list])
        else
          puts 'Some Error'
        end
      end
    end
  end
end
```

I need each module to have its own commands and/or switches. Those modules called by `--module/-m` switch. The problem is, when I use  `--list` switch trollop sees it as an argument for cooltool since its cooltool's stdin
```
 ruby cooltool.rb -m module1 --list user.txt

Error: unknown argument '-l'.
Try --help for help.
```

Thanks

**Comment by Fryguy** [comment]
This is already handled using [Commands](https://github.com/ManageIQ/trollop/wiki/Commands).  However, commands don't use a literal switch.  You *might* be able to use a switch in a manner similar to the example, but I'm not sure.  If you don't really need the switch, see if you can get it to work like the example.

**Comment by Fryguy** [comment]
Closing this for now as the feature exists, but you can reopen if you feel strongly about supporting it via a switch as well.

**Comment by Fryguy** [comment]
You may also be interested in trollop-subcommands as discussed in #88
