### ISSUE TITLE
Please release next version

### ISSUE THREAD

**Issue by ddarbyson** [ManageIQ/trollop#96]
I’m having a heck of a time releasing using the lastest version from master. As it stand the last release on rubygem is in 2015. There has been some critical features that my program relies on, which are on master, but I cannot create my gem since Bundler will not manage gems from GitHub. Please push release to ruby gems and make my life a whole lot easier!

Thank you.

**Comment by ddarbyson** [comment]
Anyone out there?

**Comment by nanobowers** [comment]
@kbrock or @Fryguy, is this something you can do?  Not sure who has permissions to release the gem.

**Comment by ddarbyson** [comment]
I saw some chatter in thread... Any ideas on publishing next version to Rubygems ?

https://rubygems.org/gems/trollop

**Comment by kbrock** [comment]
To be honest, the biggest issue is updating https://github.com/ManageIQ/trollop/blob/master/History.txt with all the wonderful PRs from people like @nanobowers

**Comment by ddarbyson** [comment]
I’m a bit new to the project so I’m not sure if I would be best suited to do this. Sounds like someone familiar and who has accepted the PR could get it done in a hour.

**Comment by ddarbyson** [comment]
@kbrock i'm not sure if we are going to get a nice updated History.txt... can you release the gem anyway?

**Comment by ddarbyson** [comment]
hi @nanobowers did you see @kbrock comment? I would really appreciate you guys updating Rubygems since the last release `2.1.2 - March 11, 2015` was over 3 years ago. 

I'm compiling projects, and Bundler doesn't make it easy when you have in include Trollop as a 'git' source... 

Looks like @kbrock was waiting on https://github.com/ManageIQ/trollop/blob/master/History.txt to be update before he will release. Would you mind spending a small amount of time to update History.txt for us??

**Comment by nanobowers** [comment]
@ddarbyson @kbrock Tried my best to satisfy the request in PR #98

**Comment by kbrock** [comment]
next release will change the name.

wanted code to be up to date before changing name
(again sorry for the delay on that front)

thanks again @nanobowers for all your help
